### ISSUE TITLE
relationships

### ISSUE THREAD

**Issue by aaronbond** [mdennis10/EasyLite-Orm#2]
if i have two classes (Book and Author) like so:

class Book{
private Author author;
}

when i get my class 'Book' from the database its private member 'author' is null. how do i handle relationships between classes like in the example?

**Comment by mdennis10** [comment]
Currently EasyLiteOrm does not support relationships, However you can store the primary key of Author entity within the Book class and then use it to fetch  a Author instance using a AuthorDao. e.g

@Entity
class Book {
   public long authorId;
}

EasyLite.getInstance(context)
              .getDao(Author.class)
              .findById(book.authorId);

Relationships will be added in the new upcoming release but I'm still thinking about the best way to implement it.

**Comment by XaeroDegreaz** [comment]
Why not implement the JPA spec?

**Comment by mdennis10** [comment]
That is something I can look into
