### ISSUE TITLE
Initialize Database

### ISSUE THREAD

**Issue by M-Razavi** [mdennis10/EasyLite-Orm#3]
Hi
When app start for first time, I want to create DB, Tables and fill them. how can I do it?
(I want to do these works only once)

Thanks in advance

**Comment by mdennis10** [comment]
EasyLite will automatically create database and tables for you. All you need to do is define the name of the database, version and package name for you entity classes https://github.com/mdennis10/EasyLite-Orm/wiki/Configuration. You will need to create and model your entity classes https://github.com/mdennis10/EasyLite-Orm/wiki/Entity-Modeling. These classes will be used by the framework to create the structure of your tables. This will be done only once unless you choose to upgrade the database by incrementing the version

All you have to do is call EasyLite.getInstance(context).getDao(Entity.class) then use one of the create methods available to save instances into the database. 

Now for the specific problem you want to solve. EasyLite doesn't contain any feature to accomplish this out of the box but you can use the features available to create a custom solution. If you need more help with coming up with a custom solution you can let me know.

**Comment by M-Razavi** [comment]
Thanks a lot Dennis
I've done all you said in Configuration and Entity-Modeling, But If i want to fill the database, only in the first run of application, How can I do it?
I think a initDb() method should be responsible for it, but i don't know who should call it.

**Comment by mdennis10** [comment]
Here is a gist with a very basic example:
https://gist.github.com/mdennis10/eaf0f8c71c89d5fdf804

MyApplication class will be called first every time the application starts. Here you check if data already exist in the table and write code to insert data if not.

**Comment by M-Razavi** [comment]
I really appreciate this.
