### ISSUE TITLE
Composite key support

### ISSUE THREAD

**Issue by EyalPerry** [mdennis10/EasyLite-Orm#4]
Hi! Are composite keys supported by your ORM?
for instance, I would like to create a table whose key is a string, int tuple?
what are the limitations, if any, on this?

If composite keys are indeed supported, you should mention this in the wiki!

Good job with the decoupling of the POJO from the framework!

**Comment by mdennis10** [comment]
Composite keys are not supported as yet. I might look into adding it to a upcoming release. The ORM is still very young and many new features are on they way.

**Comment by EyalPerry** [comment]
Good luck!

**Comment by mdennis10** [comment]
Thanks have some exciting new features coming. Stay tuned!!!
